import{a as E,S as v,i as l}from"./assets/vendor-C4-ZuMk8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function h(r,e,n=1,a=15){try{return(await E.get("https://pixabay.com/api/",{params:{key:e,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a}})).data}catch(t){throw console.error("Error fetching images:",t),new Error("Failed to fetch images")}}function b(r){return r.map(e=>`
    <a href="${e.largeImageURL}" class="gallery-item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      <div class="info">
        <p> ${e.likes} </br> Likes</p>
        <p> ${e.views} </br> Views</p>
        <p> ${e.comments} </br> Comments</p>
        <p> ${e.downloads} </br> Downloads</p>
      </div>
    </a>
  `).join("")}const w="46893136-84096bff0dd45fd4b99afcbdb",p=document.querySelector("#search-form"),y=document.querySelector("#gallery"),u=document.querySelector("#loader"),i=document.querySelector("#load-more-btn");let L=new v(".gallery a"),f="",d=1;const c=15;let g=0,s=[];p.addEventListener("submit",async function(r){if(r.preventDefault(),f=p.querySelector("input").value.trim(),d=1,s=[],!f){l.warning({title:"Warning",message:"Please enter a search keyword."});return}y.innerHTML="",u.style.display="block",i.style.display="none";try{const e=await h(f,w,d,c);if(g=e.totalHits,e.hits.length===0)l.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});else{const n=e.hits.filter(a=>!s.some(t=>t.webformatURL===a.webformatURL));s=[...s,...n],y.innerHTML=b(s),L.refresh(),n.length===c&&g>c&&(i.style.display="block")}}catch(e){l.error({title:"Error",message:"Something went wrong, please try again later."}),console.error("Error fetching images:",e)}finally{u.style.display="none"}});i.addEventListener("click",async function(){d+=1,u.style.display="block",i.style.display="none";try{const r=await h(f,w,d,c);if(r.hits.length>0){const e=r.hits.filter(n=>!s.some(a=>a.webformatURL===n.webformatURL));s=[...s,...e],y.insertAdjacentHTML("beforeend",b(s)),L.refresh(),e.length<c||d*c>=g?(l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),i.style.display="none"):i.style.display="block",S()}else l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),i.style.display="none"}catch(r){l.error({title:"Error",message:"Something went wrong, please try again later."}),console.error("Error loading more images:",r)}finally{u.style.display="none"}});function S(){const r=y.firstElementChild;if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*3,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
